[package]
name = "snes_image_encoder"
version = "0.1.0"
authors = ["khanism <khanism90@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmp = "*"